name: 'Go Tests'
description: 'Eine Action, um Go-Tests auszuführen'

inputs:
  go-version:
    description: 'Die Version von Go, die verwendet werden soll'
    required: true
    default: '1.16'

runs:
  using: 'composite'
  steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run go test
      run: go test ./...
      shell: bash
