name: 'Deploy Docker to DigitalOcean'
description: Deploys a Docker container to DigitalOcean

inputs:
  docker-user:
    description: 'DockerHub username'
    required: true
  docker-password:
    description: 'DockerHub password'
    required: true
  digital-ocean-ip:
    description: 'DigitalOcean droplet IP address'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  server-host:
    description: 'Server host'
    required: true
  server-username:
    description: 'Server username'
    required: true
  ssh-private-key:
    description: 'SSH private key'
    required: true
  ssh-port:
    description: 'SSH port'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Login to DockerHub
      run: echo "${{ inputs.docker-password }}" | docker login -u "${{ inputs.docker-user }}" --password-stdin
      shell: bash

    - name: Start SSH Agent and Add Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Setup SSH and deploy
      uses: appleboy/ssh-action@v.0.1.3
      with:
        host: ${{ inputs.server-host }}
        username: ${{ inputs.server-username }}
        key: ${{ inputs.ssh-private-key }}
        port: ${{ inputs.ssh-port }}
        script: |
          echo "Deploying via SSH"
          # Your deployment commands here
          docker pull ${{ inputs.docker-user }}/${{ inputs.image-name }}
          docker stop ${{ inputs.image-name }} || true
          docker rm ${{ inputs.image-name }} || true
          docker rmi ${{ inputs.docker-user }}/${{ inputs.image-name }}:current || true
          docker tag ${{ inputs.docker-user }}/${{ inputs.image-name }}:latest ${{ inputs.docker-user }}/${{ inputs.image-name }}:current
          docker run -d --restart always --name ${{ inputs.image-name }} -p 80:80 ${{ inputs.docker-user }}/${{ inputs.image-name }}:current