name: 'Deploy Docker to DigitalOcean'
description: Deploys a Docker container to DigitalOcean

inputs:
  docker-user:
    description: 'DockerHub username'
    required: true
  docker-password:
    description: 'DockerHub password'
    required: true
  digital-ocean-ip:
    description: 'DigitalOcean droplet IP address'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  server-host:
    description: 'Server host'
    required: true
  server-username:
    description: 'Server username'
    required: true
  ssh-private-key:
    description: 'SSH private key'
    required: true
  ssh-port:
    description: 'SSH port'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to DockerHub
      run: echo "${{ inputs.docker-password }}" | docker login -u "${{ inputs.docker-user }}" --password-stdin
      shell: bash

    - name: Start SSH Agent and Add Key
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ inputs.ssh-private-key }}" | tr -d '\r' | ssh-add -
      shell: bash

    - name: Setup SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}';
          docker pull ${{ secrets.DOCKER_USERNAME }}/repodemo;
          docker stop repodemo || true;
          docker rm repodemo || true;
          docker rmi ${{ secrets.DOCKER_USERNAME }}/repodemo:current || true;
          docker tag ${{ secrets.DOCKER_USERNAME }}/repodemo:latest ${{ secrets.DOCKER_USERNAME }}/repodemo:current;
          docker run -d --restart always --name repodemo -p 80:80 ${{ secrets.DOCKER_USERNAME }}/repodemo:current
        "
      shell: bash
